In [1]:
 import pandas as pd
 import numpy as np
 from sklearn.model_selection import train_test_split
 from sklearn.preprocessing import OneHotEncoder

In [7]:
input_file = '../data/nafld1.csv'
df = pd.read_csv(input_file)
display(df.head())

,Unnamed: 0,id,age,male,weight,height,bmi,case.id,futime,status
0,3631,1,57,0,60.0,163.0,22.690939,10630.0,6261,0
1,8458,2,67,0,70.4,168.0,24.884028,14817.0,624,0
2,6298,3,53,1,105.8,186.0,30.453537,3.0,1783,0
3,15398,4,56,1,109.3,170.0,37.830100,6628.0,3143,0
4,13261,5,68,1,NaN,NaN,NaN,1871.0,1836,1

In [8]:
    df.dropna(inplace=True)
    df.drop_duplicates(inplace=True)
    print(df.shape)

(12562, 10)

In [10]:
if "male" in df.columns:
      encoder = OneHotEncoder(drop='if_binary')
      df[['male']] = encoder.fit_transform(df[['male']]).toarray()

       #Remover coluna caso o dataset ja esteja em formato numerico, com labels 0 e 1.
display(df.head())

,Unnamed: 0,id,age,male,weight,height,bmi,case.id,futime,status
0,3631,1,57,0.0,60.0,163.0,22.690939,10630.0,6261,0
1,8458,2,67,0.0,70.4,168.0,24.884028,14817.0,624,0
2,6298,3,53,1.0,105.8,186.0,30.453537,3.0,1783,0
3,15398,4,56,1.0,109.3,170.0,37.830100,6628.0,3143,0
5,14423,6,39,0.0,63.9,155.0,26.615590,7144.0,1581,0

In [11]:
 train_data, test_data = train_test_split(df, test_size=0.3, random_state=42)
 train_data.to_csv('../data/train_data.csv', index=False)
 test_data.to_csv('../data/test_data.csv', index=False)
 print("Dados pré-processados salvos!")

Dados pré-processados salvos!